/// Flutter icons CustomMathIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomMathIcons
///      fonts:
///       - asset: fonts/CustomMathIcons.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class CustomMathIcons {
  CustomMathIcons._();

  static const _kFontFam = 'CustomMathIcons';
  static const String? _kFontPkg = null;

  static const IconData shift = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData derevative = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dx_dy = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shift_lock = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sqrt = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sqrt_extended = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lim = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData integral = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indefinite_integral = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frac = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exp = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData abs = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
